### PR TITLE
Implement RabbitMQ

### LINKED ISSUE #2: Implement RabbitMQ message broker

### PR DESCRIPTION
**Pull request by mennohie**

### CODE REVIEW

**Comment by emilssipols11** [comment]
can you also add an example maybe how one of the services would use rabbitmq to publish and subscribe to the data?

**Comment by mennohie** [comment]
> can you also add an example maybe how one of the services would use rabbitmq to publish and subscribe to the data?

I have added an example, please see if it is clear how we were to use it.

The producer will work out fine in flask, but maybe we need to somehow give a consumer listener to a daemon because we cannot have two listeners working at the same time on a single thread. I can try to figure out how to do that.

**Comment by mennohie** [comment]
Alternatively, we can create a consumer service that listens for new messages and routes the right requests to the right endpoints. Perhaps I would prefer that option

**Comment by daniel-chou-rainho** [comment]
lgtm, pull into main?

**Pull request merged**
